name: Build and deploy Python app to Azure Web App - databurn

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and Start virtual environment and Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
                
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: "183499d5-cb81-4c2a-8abf-cedf77d8ea70"
          tenant-id: "11dbbfe2-89b8-4549-be10-cec364e59551"
          subscription-id: "0a6337c5-7ac8-46e7-9b15-00b8fb6c51da"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'databurn'
          slot-name: 'Production'
          startup-command: 'python -m streamlit run app.py --server.port 8000 --server.address 0.0.0.0'
