name: Deploy DataBurn to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Login no Azure via OIDC
      uses: azure/login@v2
      with:
        client-id: "a48945a2-15c5-49ca-a9fd-e556c0aab84b"
        tenant-id: "0a6337c5-7ac8-46e7-9b15-00b8fb6c51da"
        subscription-id: "0a6337c5-7ac8-46e7-9b15-00b8fb6c51da"

    - name: Deploy para o Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "databurn"
